# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Musings on geek stuff by a chemistry electronics repairman. 
email: ddwheel@me.com
description: > # this means to ignore newlines until "baseurl:"
  This site serves as my musings on science, technology, and the repair work I 
  perform on a day-to-day basis. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mskblackbelt.github.io" # the base hostname & protocol for your site
twitter_username: mskblackbelt
github_username:  mskblackbelt

# Build settings
markdown: kramdown
